version: "2"

services:
  tika:
    image: docker.io/smalswebtech/tika-server:latest
    container_name: tika
    networks:
      - default
    mem_limit: 512m

  postgresql:
    image: docker.io/postgres:12
    container_name: postgresql
    environment:
      - POSTGRES_USER=${BATS_ROOT_DB_USER}
      - POSTGRES_PASSWORD=${BATS_ROOT_DB_PASSWORD}
      - POSTGRES_DB=${BATS_ROOT_DB_NAME}
    networks:
      - default
    mem_limit: 512m

  elasticms:
    image: docker.io/elasticms/admin:latest
    container_name: ems
    ports:
      - 9000:9000
    environment: 
      - PHP_FPM_MAX_CHILDREN=${BATS_PHP_FPM_MAX_CHILDREN}
      - PHP_FPM_REQUEST_MAX_MEMORY_IN_MEGABYTES=${BATS_PHP_FPM_REQUEST_MAX_MEMORY_IN_MEGABYTES}
      - CONTAINER_HEAP_PERCENT=${BATS_CONTAINER_HEAP_PERCENT}
      - ES_ENDPOINT_URL=${BATS_ES_LOCAL_ENDPOINT_URL}
      - TIKA_ENDPOINT_URL=${BATS_TIKA_LOCAL_ENDPOINT_URL}
      - DB_DRIVER=${BATS_DB_DRIVER}
      - DB_HOST=${BATS_DB_HOST}
      - DB_PORT=${BATS_DB_PORT}
      - DB_USER=${BATS_DB_USER}
      - DB_PASSWORD=${BATS_DB_PASSWORD}
      - DB_NAME=${BATS_DB_NAME}
    links:
      - ${BATS_STORAGE_SERVICE_NAME}:${BATS_STORAGE_SERVICE_NAME}
    depends_on:
      - ${BATS_STORAGE_SERVICE_NAME}
    command: ["wait-for-it", "${BATS_DB_HOST}:${BATS_DB_PORT}", "--", "/usr/bin/supervisord", "-c", "/etc/supervisord/supervisord.conf"]
    volumes:
      - data_ems:/var/lib/ems
      - config_ems:/opt/configs
    networks:
      - default
    mem_limit: 512m

  skeleton:
    image: ${BATS_ELASTICMS_WEBSITE_SKELETON_DOCKER_IMAGE_NAME}
    container_name: emsch
    ports:
      - 9001:9000
      - 6081:6081
    environment:
      - PHP_FPM_MAX_CHILDREN=${BATS_PHP_FPM_MAX_CHILDREN}
      - PHP_FPM_REQUEST_MAX_MEMORY_IN_MEGABYTES=${BATS_PHP_FPM_REQUEST_MAX_MEMORY_IN_MEGABYTES}
      - CONTAINER_HEAP_PERCENT=${BATS_CONTAINER_HEAP_PERCENT}
      - ES_ENDPOINT_URL=${BATS_ES_LOCAL_ENDPOINT_URL}
      - HTPASSWD_USERNAME=${BATS_HTPASSWD_USERNAME}
      - HTPASSWD_PASSWORD=${BATS_HTPASSWD_PASSWORD}
      - APACHE_ACCESS_CONTROL_ALLOW_ORIGIN=${BATS_APACHE_ACCESS_CONTROL_ALLOW_ORIGIN}
      - VARNISH_ENABLED=${BATS_VARNISH_ENABLED}
    networks:
      - default
    volumes:
      - data_ems:/var/lib/ems
      - config_emsch:/opt/configs
    build:
      context: .
      args:
        VERSION_ARG: ${BATS_ELASTICMS_WEBSITE_SKELETON_VERSION}
        RELEASE_ARG: ${BATS_RELEASE_NUMBER}
        BUILD_DATE_ARG: ${BATS_BUILD_DATE}
        VCS_REF_ARG: ${BATS_VCS_REF}
    mem_limit: 1024m

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: es01
    environment:
      - "cluster.name=docker-cluster"  
      - "node.name=es01"
      - "discovery.seed_hosts=es02,es03"
      - "cluster.initial_master_nodes=es01,es02,es03"
      - "bootstrap.memory_lock=true"
      - "node.store.allow_mmap=false"
      - "index.store.type=niofs"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - default
    mem_limit: 1024m
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: es02
    environment:
      - "cluster.name=docker-cluster"  
      - "node.name=es02"
      - "discovery.seed_hosts=es01,es03"
      - "cluster.initial_master_nodes=es01,es02,es03"
      - "bootstrap.memory_lock=true"
      - "node.store.allow_mmap=false"
      - "index.store.type=niofs"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - default
    mem_limit: 1024m
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: es03
    environment:
      - "cluster.name=docker-cluster"  
      - "node.name=es03"
      - "discovery.seed_hosts=es01,es02"
      - "cluster.initial_master_nodes=es01,es02,es03"
      - "bootstrap.memory_lock=true"
      - "node.store.allow_mmap=false"
      - "index.store.type=niofs"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - default
    mem_limit: 1024m

volumes:
  data_ems:
    external:
      name: ${BATS_EMS_STORAGE_VOLUME_NAME}
  config_ems:
    external:
      name: ${BATS_EMS_CONFIG_VOLUME_NAME}
  config_emsch:
    external:
      name: ${BATS_EMSCH_CONFIG_VOLUME_NAME}

networks:
  default:
    external:
      name: docker_default
