name: Continuous Docker Image Build

on:
  push:
    branches:
      - '**'

  pull_request:

jobs:

  build-docker-images:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2

      - uses: actions/checkout@v3.0.2
        with:
          repository: ems-project/elasticms-demo
          path: test/demo

      - name: Prepare Elasticms Demo Project
        id: prep_demo
        run: |
          mkdir -p test/demo/dist
          npm install --save-dev webpack --prefix test/demo test/demo
          npm run --prefix test/demo prod
          chmod 777 -Rf test/demo

      - name: Fill GitHub Environment Variables
        uses: FranzDiebold/github-env-vars-action@v2.3.1

      - name: Setup BATS testing framework
        uses: mig4/setup-bats@v1.2.0
        with:
          bats-version: 1.2.1

      - name: Fill PHP Version Environment Variable
        uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .build.env

      - name: Prepare Workflow Environment
        id: prep
        run: |
          docker network create docker_default
          docker pull appropriate/curl:latest
          IMAGENAME_PRD=docker.io/elasticms/website-skeleton
          IMAGENAME_DEV=docker.io/elasticms/website-skeleton-dev
          VERSION_MAJOR_MINOR_PATCH=${{ env.ELASTICMS_WEBSITE_SKELETON_VERSION }}
          VERSION_MAJOR_MINOR=${VERSION_MAJOR_MINOR_PATCH%.*}
          VERSION_MAJOR=${VERSION_MAJOR_MINOR%.*}
          echo ::set-output name=imagename_prd::${IMAGENAME_PRD}
          echo ::set-output name=imagename_dev::${IMAGENAME_DEV}
          echo ::set-output name=version_major_minor_patch::${VERSION_MAJOR_MINOR_PATCH}
          echo ::set-output name=version_major_minor::${VERSION_MAJOR_MINOR}
          echo ::set-output name=version_major::${VERSION_MAJOR}
          echo ::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Fill Prod Image metadata
        id: meta_prd
        uses: crazy-max/ghaction-docker-meta@v4.0.1
        with:
          images: "${{ steps.prep.outputs.imagename_prd }}"
          tags: |
            type=raw,value=${{ env.CI_SHA_SHORT }}
            type=raw,value=${{ steps.prep.outputs.version_major_minor_patch }}
            type=raw,value=${{ steps.prep.outputs.version_major_minor }}
            type=raw,value=${{ steps.prep.outputs.version_major }}
            type=raw,value=latest

      - name: Fill Dev Image metadata
        id: meta_dev
        uses: crazy-max/ghaction-docker-meta@v4.0.1
        with:
          images: "${{ steps.prep.outputs.imagename_dev }}"
          tags: |
            type=raw,value=${{ env.CI_SHA_SHORT }}
            type=raw,value=${{ steps.prep.outputs.version_major_minor_patch }}
            type=raw,value=${{ steps.prep.outputs.version_major_minor }}
            type=raw,value=${{ steps.prep.outputs.version_major }}
            type=raw,value=latest

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Cache Docker layers
        uses: actions/cache@v3.0.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Prod Docker Image
        id: build_prd
        uses: docker/build-push-action@v3.0.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile
          target: emsch-prod
          build-args: |
            VERSION_ARG=${{ env.ELASTICMS_WEBSITE_SKELETON_VERSION }}
            RELEASE_ARG=${{ env.CI_RUN_ID }}
            VCS_REF_ARG=${{ env.CI_SHA }}
            BUILD_DATE_ARG=${{ steps.prep.outputs.build_date }}
          push: false
          load: true
          tags: ${{ steps.meta_prd.outputs.tags }}
          labels: ${{ steps.meta_prd.outputs.labels }}

      - name: Build Dev Docker Image
        id: build_dev
        uses: docker/build-push-action@v3.0.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile
          target: emsch-dev
          build-args: |
            VERSION_ARG=${{ env.ELASTICMS_WEBSITE_SKELETON_VERSION }}
            RELEASE_ARG=${{ env.CI_RUN_ID }}
            VCS_REF_ARG=${{ env.CI_SHA }}
            BUILD_DATE_ARG=${{ steps.prep.outputs.build_date }}
          push: false
          load: true
          tags: ${{ steps.meta_dev.outputs.tags }}
          labels: ${{ steps.meta_dev.outputs.labels }}

#      - name: Scan Prod Docker Image
#        uses: azure/container-scan@v0
#        with:
#          image-name: ${{ steps.prep.outputs.imagename_prd }}:${{ env.CI_SHA_SHORT }}
#          severity-threshold: CRITICAL

      - name: Test Prod Docker Image
        env:
          ELASTICMS_WEBSITE_SKELETON_DOCKER_IMAGE_NAME: ${{ steps.prep.outputs.imagename_prd }}:${{ env.CI_SHA_SHORT }}
        run: |
          bats -r test/tests.bats

      - name: Push Prod Docker Image
        id: push_prd
        uses: docker/build-push-action@v3.0.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile
          target: emsch-prod
          build-args: |
            VERSION_ARG=${{ env.ELASTICMS_WEBSITE_SKELETON_VERSION }}
            RELEASE_ARG=${{ env.CI_RUN_ID }}
            VCS_REF_ARG=${{ env.CI_SHA }}
            BUILD_DATE_ARG=${{ steps.prep.outputs.build_date }}
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta_prd.outputs.tags }}
          labels: ${{ steps.meta_prd.outputs.labels }}

      - name: Push Dev Docker Image
        id: push_dev
        uses: docker/build-push-action@v3.0.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile
          target: emsch-dev
          build-args: |
            VERSION_ARG=${{ env.ELASTICMS_WEBSITE_SKELETON_VERSION }}
            RELEASE_ARG=${{ env.CI_RUN_ID }}
            VCS_REF_ARG=${{ env.CI_SHA }}
            BUILD_DATE_ARG=${{ steps.prep.outputs.build_date }}
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta_dev.outputs.tags }}
          labels: ${{ steps.meta_dev.outputs.labels }}

      - name: Check Prod Docker Image
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        run: |
          docker buildx imagetools inspect ${{ steps.prep.outputs.imagename_prd }}:${{ steps.prep.outputs.version_major_minor_patch }}

      - name: Check Dev Docker Image
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        run: |
          docker buildx imagetools inspect ${{ steps.prep.outputs.imagename_dev }}:${{ steps.prep.outputs.version_major_minor_patch }}

      - name: Check Prod Docker Images pull's
        if: github.GHCR != 'pull_request' && github.ref == 'refs/heads/master'
        run: |
          docker pull ${{ steps.prep.outputs.imagename_prd }}:${{ steps.prep.outputs.version_major_minor_patch }}

      - name: Check Dev Docker Images pull's
        if: github.GHCR != 'pull_request' && github.ref == 'refs/heads/master'
        run: |
          docker pull ${{ steps.prep.outputs.imagename_dev }}:${{ steps.prep.outputs.version_major_minor_patch }}
